# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    image: mysql
    restart: always
    command: --lower_case_table_names=1
    environment:
      MYSQL_DATABASE: 'mydb'
      MYSQL_ROOT_PASSWORD: example
    ports:
       -   3306:3306